### ISSUE TITLE
卡在百分之0

### ISSUE THREAD

**Issue by raindrop213** [VermiIIi0n/fuckBookWalker#1]
换号也一样，始终是百分之0
![~HH 8X_ CW0YH%HHYTE)FNV](https://github.com/VermiIIi0n/fuckBookWalker/assets/53202747/d07aa326-2f7c-4a47-8034-a4e33e5eceb7)
![PAUT(T79S 68 VDVVG2LFA6](https://github.com/VermiIIi0n/fuckBookWalker/assets/53202747/3948e514-0252-44ac-a245-3deb00b82ef8)
![@QGSOTDR91(6Q5N@_RB(8GW](https://github.com/VermiIIi0n/fuckBookWalker/assets/53202747/28740320-b8db-4677-88c2-b6e9f196c68b)

不知道是什么问题呢

**Comment by VermiIIi0n** [comment]
你可以在设置里把 headless 关了，这样可以看到脚本的具体操作。

如果是第一次在某地IP下运行可能会遇到人机验证，你也可以先手动登陆查看一遍书籍。

如果还存在问题欢迎上传下调试日志和告知下具体操作，我会尝试复现一下。

**Comment by raindrop213** [comment]
![1714557847557](https://github.com/VermiIIi0n/fuckBookWalker/assets/53202747/6d63a80b-4040-411c-b88d-5a9c605b2fce)
改成false，然后看到运行过程，现在还是卡在0，即使程序已经顺利自动打开书了，我也翻了个遍，也还是0

**Comment by raindrop213** [comment]
![327103859-051225fb-0888-43c3-8a64-f5ce1e57e31d](https://github.com/VermiIIi0n/fuckBookWalker/assets/53202747/c1e1a12d-8389-4845-a947-64860ed5056a)

创建完环境就poetry run python bookphucker "https://bookwalker.jp/defa05b1ae-3053-4536-a90c-f04f33f1e124/"
然后第一次运行时登不上号的，等很久没反应就关掉然后改成false，之后再执行，然后就是手动登号。
最后成功自动打开书本，但无论怎么翻书都是卡在0
![image](https://github.com/VermiIIi0n/fuckBookWalker/assets/53202747/8f2dd613-2ef5-4165-b496-fa72d61b32a8)

**Comment by VermiIIi0n** [comment]
抱歉之前忙没时间回复，看样子是阅读界面小改动造成没法读取阅读进度，已经修复。

**Comment by raindrop213** [comment]
非常感谢，已经成功提取图片

**Comment by VermiIIi0n** [comment]
不客气，那我就关闭这个 issue 了
