### ISSUE TITLE
Can I use it for Bookwalker.com.tw?

### ISSUE THREAD

**Issue by gigihubb** [VermiIIi0n/fuckBookWalker#2]
Can I use it for Bookwalker.com.tw?

Thank you.

**Comment by VermiIIi0n** [comment]
I'm afraid not, but I will try to add this feature soon.😊

**Comment by gigihubb** [comment]
> I'm afraid not, but I will try to add this feature soon.😊

Great, thank you!

**Comment by JasChiang** [comment]
<img width="578" alt="image" src="https://github.com/VermiIIi0n/fuckBookWalker/assets/1609308/a9ccd3ee-8cf2-4b11-b35f-5a0e1743b32d">

Can I use it on Mac? It got stuck here. thx :D

**Comment by Kifany** [comment]
Hello, Bookwalker TW needs UTF-8 encoding to download books in Chinese name otherwise it will occurs an encode error. 
I added a encoding command to solve the problem , located at \bookphucker\tw.py line 127-129
```python
    meta_path.write_text(json.dumps(
        {"title": title, "authors": authors},
        ensure_ascii=False, indent=2), encoding = "utf-8")
``` 
Download some recently published books successfully. Thank you so much.

**Comment by VermiIIi0n** [comment]
> Hello, Bookwalker TW needs UTF-8 encoding to download books in Chinese name otherwise it will occurs an encode error. I added an encoding command to solve the problem , located at \bookphucker\tw.py line 127-129
> 
> ```python
>     meta_path.write_text(json.dumps(
>         {"title": title, "authors": authors},
>         ensure_ascii=False, indent=2), encoding = "utf-8")
> ```
> 
> Download some recently published books successfully. Thank you so much.

Ah yes, thank you! I didn't test it on Windows and all of my systems use UTF-8 by default so this bug escaped my eyes. I will fix it later.
